name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Read version file and set VERSION
        run: |
          VERSION="${{ github.run_id }}"
          echo "VERSION=${VERSION,,}" >> $GITHUB_ENV

          FULL_IMAGE_PATH="ghcr.io/${{ github.repository }}"
          echo "FULL_IMAGE_PATH=${FULL_IMAGE_PATH,,}" >> $GITHUB_ENV

          REPO_NAME="${{ github.repository }}"
          echo "REPO_NAME=${REPO_NAME##*/}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.FULL_IMAGE_PATH }}:${{ env.VERSION }}
            ${{ env.FULL_IMAGE_PATH }}:latest
          file: ./Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Create local tarball
        run: |
          mkdir -p releases
          docker save "${{ env.FULL_IMAGE_PATH }}:${{ env.VERSION }}" | gzip > "releases/${{ env.REPO_NAME }}.${{ env.VERSION }}.tar.gz"

      - name: Upload tarball artifact
        uses: actions/upload-artifact@v4
        with:
          name: image-tar
          path: releases/${{ env.REPO_NAME }}.${{ env.VERSION }}.tar.gz
